# Travis-CI Build for libbootimg
# see travis-ci.org for details

language: c

os: linux
dist: bionic

compiler:
  - gcc
  - clang

jobs:
  include:
    - os: linux
      dist: trusty
      compiler: i586-mingw32msvc-gcc
    - os: osx
      compiler: clang

script:
  - cd src && make

# Only watch the master
branches:
  only:
    - test
